<a href="https://colab.research.google.com/github/MIDHUN22/data-science/blob/main/exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from timeit import Timer

array = np.random.randint(1000,size=10**5)
def sum_using_forloop():
  sum_array=0
  for element in array:
    sum_array += element
    
def sum_using_builtin_method():
  sum_array= sum(array)
  
def sum_using_numpy():
  sum_array = np.sum(array)

time_forloop = Timer(sum_using_forloop).timeit(1)
time_builtin = Timer(sum_using_builtin_method).timeit(1)
time_numpy = Timer(sum_using_numpy).timeit(1)

print(time_forloop)
print(time_builtin)
print(time_numpy)
print() 
   


sum ^

In [13]:
import numpy as np
a=[[1,0],[0,1]]
b=[[4,1],[2,2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])

dot product ^

In [17]:
import numpy as np

matrix1 = np.array([[1,3],[2,6]])
matrix2 = np.array([[0,1],[1,9]])

print("original 2d matrix is:")
print(matrix1)
print(matrix2)

print("Outer Product of the two matrix is:")
result = np.outer(matrix1,matrix2)
print(result)

original 2d matrix is:
[[1 3]
 [2 6]]
[[0 1]
 [1 9]]
Outer Product of the two matrix is:
[[ 0  1  1  9]
 [ 0  3  3 27]
 [ 0  2  2 18]
 [ 0  6  6 54]]


outer product^

In [20]:
import numpy as np

in_arr1 = np. array([[2,7,5],[-6,2,0]])
in_arr2 = np.array([[0,-7,8],[5,-2,9]])

print("array 1 input:", in_arr1)
print("array 2 unput:",in_arr2)

out_arr = np.multiply(in_arr1, in_arr2)
print(out_arr)

array 1 input: [[ 2  7  5]
 [-6  2  0]]
array 2 unput: [[ 0 -7  8]
 [ 5 -2  9]]
[[  0 -49  40]
 [-30  -4   0]]


product^